export const PRODUTO_LIST_REQUEST = 'PRODUTO_LIST_REQUEST';
export const PRODUTO_LIST_SUCESSO = 'PRODUTO_LIST_SUCESSO';
export const PRODUTO_LIST_FALHA = 'PRODUTO_LIST_FALHA';

export const PRODUTO_DETALHES_REQUEST = 'PRODUTO_DETALHES_REQUEST';
export const PRODUTO_DETALHES_SUCESSO = 'PRODUTO_DETALHES_SUCESSO';
export const PRODUTO_DETALHES_FALHA = 'PRODUTO_DETALHES_FALHA';
