export const USUARIO_ENTRAR_CONTA_REQUEST = 'USUARIO_ENTRAR_CONTA_REQUEST';
export const USUARIO_ENTRAR_CONTA_SUCESS = 'USUARIO_ENTRAR_CONTA_SUCESS';
export const USUARIO_ENTRAR_CONTA_FAIL = 'USUARIO_ENTRAR_CONTA_FAIL';
export const USUARIO_SAIR_CONTA = 'USUARIO_SAIR_CONTA';
