export const SALVAR_ENDERECO_ENVIO_REQUEST = 'SALVAR_ENDERECO_ENVIO_REQUEST';
export const SALVAR_ENDERECO_ENVIO_SUCESSO = 'SALVAR_ENDERECO_ENVIO_SUCESSO';
export const SALVAR_ENDERECO_ENVIO_FALHA = 'SALVAR_ENDERECO_ENVIO_REQUEST';
