export const PEDIDO_CRIA_REQUEST = 'PEDIDO_CRIA_REQUEST'
export const PEDIDO_CRIA_SUCESSO = 'PEDIDO_CRIA_SUCESSO'
export const PEDIDO_CRIA_FALHA = 'PEDIDO_CRIA_FALHA'
export const PEDIDO_CRIADO_RESET = 'PEDIDO_CRIADO_RESET'
export const CARRINHO_VAZIO = 'CARRINHO_VAZIO'



export const DETALHES_PEDIDO_REQUEST = 'DETALHES_PEDIDO_REQUEST'
export const DETALHES_PEDIDO_SUCESSO = 'DETALHES_PEDIDO_SUCESSO'
export const DETALHES_PEDIDO_FALHA = 'DETALHES_PEDIDO_FALHA'

