import bcrypt from 'bcryptjs';
export const dados = {
  usuarios: [
    {
      nome: 'erivanio',
      email: 'admin@example.com',
      senha: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      nome: 'liliane',
      email: 'liliane@example.com',
      senha: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  produtos: [
    {
      // _id: '1',
      nome: 'Nike Slim Shirt',
      categoria: 'Shirts',
      image: '/imagens/p1.jpg',
      preco: 120,
      quantidadeEmEstoque: 10,
      marca: 'Nike',
      avaliacao: 4.5,
      numVisualizacoes: 10,
      descricao: 'high quality product',
    },
    {
      // _id: '2',
      nome: 'Adidas Fit Shirt',
      categoria: 'Shirts',
      image: '/imagens/p2.jpg',
      preco: 100,
      quantidadeEmEstoque: 20,
      marca: 'Adidas',
      avaliacao: 1.0,
      numVisualizacoes: 10,
      descricao: 'high quality product',
    },
    {
      // _id: '3',
      nome: 'Lacoste Free Shirt',
      categoria: 'Shirts',
      image: '/imagens/p3.jpg',
      preco: 220,
      quantidadeEmEstoque: 0,
      marca: 'Lacoste',
      avaliacao: 4.8,
      numVisualizacoes: 17,
      descricao: 'high quality product',
    },
    {
      // _id: '4',
      nome: 'Nike Slim Pant',
      categoria: 'Pants',
      image: '/imagens/p4.jpg',
      preco: 78,
      quantidadeEmEstoque: 15,
      marca: 'Nike',
      avaliacao: 4.5,
      numVisualizacoes: 14,
      descricao: 'high quality product',
    },
    {
      // _id: '5',
      nome: 'Puma Slim Pant',
      categoria: 'Pants',
      image: '/imagens/p5.jpg',
      preco: 65,
      quantidadeEmEstoque: 5,
      marca: 'Puma',
      avaliacao: 4.5,
      numVisualizacoes: 10,
      descricao: 'high quality product',
    },
    {
      // _id: '6',
      nome: 'Adidas Fit Pant',
      categoria: 'Pants',
      image: '/imagens/p6.jpg',
      preco: 139,
      quantidadeEmEstoque: 12,
      marca: 'Adidas',
      avaliacao: 4.5,
      numVisualizacoes: 15,
      descricao: 'high quality product',
    },
  ],
  Caixa: [
    {
      id: 1,
      tipo: 'Entrada',
      desc: 'Saldo inicial',
      forma: 'dinheiro',
      valor: 100,
      data: '03/02/2022',
    },
    {
      id: 2,
      tipo: 'Entrada',
      desc: 'venda',
      forma: 'dinheiro',
      valor: 200,
      data: '03/02/2022',
    },
    {
      id: 3,
      tipo: 'Saídas',
      desc: 'Compra Mercadorias',
      forma: 'cartão',
      valor: 324,
      data: '03/02/2022',
    },
  ],
};
